### ISSUE TITLE
Client already exists

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ntrees/javapns#28]
```
What steps will reproduce the problem?
1. I'm running this code in ActiveMatrix as a service
2. When i call the service it states that Client already exists.
3. It appears to be hanging onto the manager  instance. is there a way to 
destroy the instance  before it tires to create it?

What is the expected output? What do you see instead?
If I run the code as a stand alone program it works fine. 
What version of the product are you using? On what operating system?
Java APNS 1..5-v1.6.2



Please provide any additional information below.

```

Original issue reported on code.google.com by `bzn...@gmail.com` on 29 Sep 2010 at 2:29

**Comment by GoogleCodeExporter** [comment]
```
i am also facing same pb....
```

Original comment by `saggamma...@gmail.com` on 4 Oct 2010 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
What is ActiveMatrix?

How is the lib being instantiated?
```

Original comment by `idbill.p...@gmail.com` on 5 Oct 2010 at 4:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `idbill.p...@gmail.com` on 16 Oct 2010 at 9:39
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
The Solution for this is very simple just remove the device after sending the 
notification  pushManager.removeDevice(); 
```

Original comment by `pankajav...@gmail.com` on 24 Nov 2010 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Hello,

Your solution is as follows:
The Solution for this is very simple just remove the device after sending the 
notification  pushManager.removeDevice(); 


Where does this need to be called.... in the main, when i call it there i get 
the follwoing error:
Removing Token from Device 
[aebf53cc8d6bfaf4eb91a389c5a3f1ab91fa5b0fc83746a14b....]

Unknown client
    at ts.javapns.back.DeviceFactory.removeDevice(DeviceFactory.java:118)
    at ts.javapns.back.PushNotificationManager.removeDevice(PushNotificationManager.java:199)
    at org.apache.jsp.japnslist_jsp._jspService(org.apache.jsp.japnslist_jsp:144)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:322)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:291)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:241)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:744)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Unknown Source)


Please help


Sergio


```

Original comment by `sguerr...@gmail.com` on 29 Jul 2011 at 2:45
